// frontend/src/components/AppShell.tsx
import { useEffect, useMemo, useState, type ReactNode, type UIEvent } from 'react'
import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom'

import { useAuth } from '../stores/auth'
import { useSocial } from '../stores/social'
import Toaster from './Toaster'

export default function AppShell({
  full = false,
  children,
  onContentScroll,
}: {
  full?: boolean
  children: ReactNode
  onContentScroll?: (event: UIEvent<HTMLDivElement>) => void
}) {
  const auth = useAuth()
  const social = useSocial()
  const navigate = useNavigate()
  const location = useLocation()
  const params = new URLSearchParams(location.search)
  const [search, setSearch] = useState(params.get('q') ?? '')

  useEffect(() => {
    setSearch(new URLSearchParams(location.search).get('q') ?? '')
  }, [location.search])

  useEffect(() => {
    if (auth.isLoggedIn) void social.refreshMine()
    else social.clear()
  }, [auth.isLoggedIn])

  const userLabel = useMemo(() => {
    if (!auth.isLoggedIn) return '未登录'
    const username = auth.claims?.username ?? '(unknown)'
    const accountId = auth.claims?.account_id
    return accountId ? `${username} #${accountId}` : username
  }, [auth.claims, auth.isLoggedIn])

  function onSearch() {
    const q = search.trim()
    void navigate(q ? `/?q=${encodeURIComponent(q)}` : '/')
  }

  return (
    <div className="dy-shell">
      <aside className="dy-aside">
        <Link className="dy-logo" to="/">
          RedNote Demo
        </Link>
        <nav className="dy-nav">
          <NavLink className="dy-nav-link" to="/">
            最新
          </NavLink>
          <NavLink className="dy-nav-link" to="/hot">
            热榜
          </NavLink>
          <NavLink className="dy-nav-link" to="/video" end>
            发布笔记
          </NavLink>
          <NavLink className="dy-nav-link" to="/account">
            账号
          </NavLink>
          {auth.isLoggedIn ? (
            <NavLink className="dy-nav-link" to="/messages">
              私信
            </NavLink>
          ) : null}
          <NavLink className="dy-nav-link" to="/settings">
            设置
          </NavLink>
        </nav>
        <div className="dy-aside-foot">
          <div className="dy-user">
            <span className={`dy-user-dot ${auth.isLoggedIn ? 'ok' : 'bad'}`} />
            <span className="dy-user-name">{userLabel}</span>
          </div>
          <button className="dy-btn dy-btn-primary" type="button" onClick={() => void navigate(auth.isLoggedIn ? '/settings' : '/account')}>
            {auth.isLoggedIn ? '设置' : '登录'}
          </button>
        </div>
      </aside>

      <div className="dy-main">
        <header className="dy-topbar">
          <div className="dy-top-left">
            <div className="dy-tabs-hint">{location.pathname}</div>
          </div>
          <div className="dy-search">
            <input
              value={search}
              className="dy-search-input"
              placeholder="搜索标题 / 作者 / 文案（本地过滤）"
              onChange={(event) => setSearch(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === 'Enter') onSearch()
              }}
            />
            <button className="dy-btn dy-btn-primary" type="button" onClick={onSearch}>
              搜索
            </button>
          </div>
          <div className="dy-top-right">
            <Link className="dy-btn dy-btn-ghost" to="/video">
              + 发布笔记
            </Link>
          </div>
        </header>

        <nav className="dy-mobile-nav">
          <NavLink className="dy-mobile-link" to="/">
            最新
          </NavLink>
          <NavLink className="dy-mobile-link" to="/hot">
            热榜
          </NavLink>
          <NavLink className="dy-mobile-link" to="/video" end>
            发布
          </NavLink>
          {auth.isLoggedIn ? (
            <NavLink className="dy-mobile-link" to="/messages">
              私信
            </NavLink>
          ) : null}
          <NavLink className="dy-mobile-link" to="/account">
            账号
          </NavLink>
        </nav>

        <div className={`dy-content ${full ? 'full' : 'padded'}`} onScroll={onContentScroll}>
          {full ? children : <div className="container">{children}</div>}
        </div>
      </div>
      <Toaster />
    </div>
  )
}

// frontend/src/components/AppShell.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import { RouterLink, useRoute, useRouter } from 'vue-router'

import { useAuthStore } from '../stores/auth'
import { useSocialStore } from '../stores/social'
import Toaster from './Toaster.vue'

const props = defineProps<{ full?: boolean }>()
const emit = defineEmits<{ (e: 'content-scroll', event: Event): void }>()

const auth = useAuthStore()
const social = useSocialStore()
const router = useRouter()
const route = useRoute()

const search = ref(typeof route.query.q === 'string' ? route.query.q : '')
watch(
  () => route.query.q,
  (v) => {
    search.value = typeof v === 'string' ? v : ''
  },
)

watch(
  () => auth.isLoggedIn,
  (v) => {
    if (v) void social.refreshMine()
    else social.clear()
  },
  { immediate: true },
)

const userLabel = computed(() => {
  if (!auth.isLoggedIn) return '未登录'
  const username = auth.claims?.username ?? '(unknown)'
  const accountId = auth.claims?.account_id
  return accountId ? `${username} #${accountId}` : username
})

async function onSearch() {
  const q = search.value.trim()
  await router.push({ path: '/', query: q ? { q } : {} })
}

async function goLogin() {
  await router.push('/account')
}

async function goSettings() {
  await router.push('/settings')
}

function onContentScroll(event: Event) {
  emit('content-scroll', event)
}
</script>

<template>
  <div class="dy-shell">
    <aside class="dy-aside">
      <RouterLink class="dy-logo" to="/">RedNote Demo</RouterLink>

      <nav class="dy-nav">
        <RouterLink class="dy-nav-link" to="/">最新</RouterLink>
        <RouterLink class="dy-nav-link" to="/hot">热榜</RouterLink>
        <RouterLink class="dy-nav-link" to="/video">发布笔记</RouterLink>
        <RouterLink class="dy-nav-link" to="/account">账号</RouterLink>
        <RouterLink v-if="auth.isLoggedIn" class="dy-nav-link" to="/messages">私信</RouterLink>
        <RouterLink class="dy-nav-link" to="/settings">设置</RouterLink>
      </nav>

      <div class="dy-aside-foot">
        <div class="dy-user">
          <span class="dy-user-dot" :class="auth.isLoggedIn ? 'ok' : 'bad'" />
          <span class="dy-user-name">{{ userLabel }}</span>
        </div>
        <div class="dy-user-actions">
          <button v-if="!auth.isLoggedIn" class="dy-btn dy-btn-primary" type="button" @click="goLogin">登录</button>
          <button v-else class="dy-btn dy-btn-primary" type="button" @click="goSettings">设置</button>
        </div>
      </div>
    </aside>

    <div class="dy-main">
      <header class="dy-topbar">
        <div class="dy-top-left">
          <div class="dy-tabs-hint">{{ route.name }}</div>
        </div>

        <div class="dy-search">
          <input v-model="search" class="dy-search-input" placeholder="搜索标题 / 作者 / 文案（本地过滤）" @keydown.enter="onSearch" />
          <button class="dy-btn dy-btn-primary" type="button" @click="onSearch">搜索</button>
        </div>

        <div class="dy-top-right">
          <RouterLink class="dy-btn dy-btn-ghost" to="/video">+ 发布笔记</RouterLink>
        </div>
      </header>

      <nav class="dy-mobile-nav">
        <RouterLink class="dy-mobile-link" to="/">最新</RouterLink>
        <RouterLink class="dy-mobile-link" to="/hot">热榜</RouterLink>
        <RouterLink class="dy-mobile-link" to="/video">发布</RouterLink>
        <RouterLink v-if="auth.isLoggedIn" class="dy-mobile-link" to="/messages">私信</RouterLink>
        <RouterLink class="dy-mobile-link" to="/account">账号</RouterLink>
      </nav>

      <div class="dy-content" :class="props.full ? 'full' : 'padded'" @scroll.passive="onContentScroll">
        <template v-if="props.full">
          <slot />
        </template>
        <template v-else>
          <div class="container">
            <slot />
          </div>
        </template>
      </div>
    </div>

    <Toaster />
  </div>
</template>

<style scoped>
.dy-shell {
  height: 100vh;
  display: grid;
  grid-template-columns: 232px 1fr;
  background: transparent;
}

.dy-aside {
  border-right: 1px solid var(--border);
  background: rgba(12, 16, 23, 0.78);
  backdrop-filter: blur(18px);
  padding: 14px 12px;
  display: flex;
  flex-direction: column;
  gap: 14px;
}

.dy-logo {
  font-weight: 900;
  letter-spacing: 0;
  font-size: 18px;
  padding: 10px 10px;
  border-radius: 8px;
  background: rgba(43, 161, 255, 0.1);
  border: 1px solid rgba(43, 161, 255, 0.22);
  text-decoration: none;
}

.dy-nav {
  display: grid;
  gap: 8px;
}

.dy-nav-link {
  padding: 10px 10px;
  border-radius: 8px;
  border: 1px solid transparent;
  background: rgba(255, 255, 255, 0.04);
  color: rgba(246, 248, 251, 0.86);
  text-decoration: none;
}

.dy-nav-link.router-link-active {
  border-color: rgba(43, 161, 255, 0.42);
  background: rgba(43, 161, 255, 0.14);
  color: rgba(246, 248, 251, 0.96);
}

.dy-aside-foot {
  margin-top: auto;
  display: grid;
  gap: 10px;
  padding-top: 12px;
  border-top: 1px solid var(--border);
}

.dy-user {
  display: flex;
  gap: 10px;
  align-items: center;
}

.dy-user-dot {
  width: 10px;
  height: 10px;
  border-radius: 999px;
  background: rgba(255, 255, 255, 0.25);
  box-shadow: 0 0 0 3px rgba(255, 255, 255, 0.06);
}

.dy-user-dot.ok {
  background: rgba(34, 197, 94, 1);
  box-shadow: 0 0 0 3px rgba(34, 197, 94, 0.14);
}

.dy-user-dot.bad {
  background: rgba(255, 93, 115, 1);
  box-shadow: 0 0 0 3px rgba(255, 93, 115, 0.14);
}

.dy-user-name {
  font-size: 13px;
  color: var(--text);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.dy-user-actions {
  display: flex;
  gap: 10px;
}

.dy-btn {
  appearance: none;
  border: 1px solid var(--border);
  background: rgba(255, 255, 255, 0.06);
  color: var(--text);
  border-radius: 8px;
  padding: 10px 12px;
  cursor: pointer;
  text-decoration: none;
  display: inline-flex;
  align-items: center;
  gap: 8px;
  justify-content: center;
  font-size: 13px;
}

.dy-btn:hover {
  background: rgba(255, 255, 255, 0.1);
}

.dy-btn-primary {
  border-color: rgba(43, 161, 255, 0.5);
  background: rgba(43, 161, 255, 0.16);
}

.dy-btn-primary:hover {
  background: rgba(43, 161, 255, 0.24);
}

.dy-btn-ghost {
  border-color: var(--border);
  background: rgba(255, 255, 255, 0.045);
}

.dy-main {
  height: 100vh;
  display: flex;
  flex-direction: column;
  min-width: 0;
}

.dy-topbar {
  height: 56px;
  border-bottom: 1px solid var(--border);
  background: rgba(12, 16, 23, 0.68);
  backdrop-filter: blur(18px);
  display: grid;
  grid-template-columns: 180px 1fr 180px;
  gap: 12px;
  align-items: center;
  padding: 0 14px;
}

.dy-tabs-hint {
  font-size: 12px;
  color: var(--muted);
  text-transform: uppercase;
  letter-spacing: 0;
}

.dy-search {
  display: grid;
  grid-template-columns: 1fr auto;
  gap: 10px;
  align-items: center;
  max-width: 680px;
  width: 100%;
  justify-self: center;
}

.dy-search-input {
  width: 100%;
  background: rgba(255, 255, 255, 0.055);
  border: 1px solid var(--border);
  border-radius: 8px;
  color: var(--text);
  padding: 10px 14px;
  outline: none;
}

.dy-search-input:focus {
  border-color: rgba(43, 161, 255, 0.52);
  box-shadow: 0 0 0 3px rgba(43, 161, 255, 0.14);
}

.dy-top-right {
  display: flex;
  justify-content: flex-end;
}

.dy-content {
  flex: 1;
  min-height: 0;
}

.dy-content.padded {
  overflow: auto;
}

.dy-content.full {
  overflow: auto;
}

.dy-mobile-nav {
  display: none;
}

@media (max-width: 900px) {
  .dy-shell {
    grid-template-columns: 1fr;
  }
  .dy-aside {
    display: none;
  }
  .dy-topbar {
    grid-template-columns: 1fr;
    padding: 0 10px;
  }
  .dy-top-left {
    display: none;
  }
  .dy-top-right {
    display: none;
  }
  .dy-mobile-nav {
    height: 48px;
    display: grid;
    grid-auto-flow: column;
    grid-auto-columns: 1fr;
    border-bottom: 1px solid var(--border);
    background: rgba(12, 16, 23, 0.74);
    backdrop-filter: blur(18px);
  }
  .dy-mobile-link {
    display: grid;
    place-items: center;
    color: var(--muted);
    font-size: 13px;
    text-decoration: none;
    border-bottom: 2px solid transparent;
  }
  .dy-mobile-link.router-link-active {
    color: var(--text);
    border-bottom-color: var(--primary);
  }
  .dy-search {
    max-width: none;
  }
}
</style>
