// frontend/src/components/FeedVideoCard.vue
<script setup lang="ts">
import type { FeedVideoItem } from '../api/types'

const props = defineProps<{
  item: FeedVideoItem
  canLike: boolean
  busy?: boolean
}>()

const emit = defineEmits<{
  (e: 'toggle-like', item: FeedVideoItem): void
}>()

function onToggle() {
  emit('toggle-like', props.item)
}
</script>

<template>
  <div class="feed-card">
    <div class="cover">
      <img :src="item.cover_url" :alt="item.title" loading="lazy" />
    </div>
    <div class="content">
      <div class="row" style="justify-content: space-between">
        <div>
          <div class="title">
            <RouterLink :to="`/video/${item.id}`">{{ item.title }}</RouterLink>
          </div>
          <div class="subtle">
            @{{ item.author.username }} · #{{ item.author.id }} · {{ new Date(item.create_time * 1000).toLocaleString() }}
          </div>
        </div>
        <div class="row">
          <span class="pill mono">❤️ {{ item.likes_count }}</span>
          <button
            v-if="canLike"
            class="primary"
            type="button"
            :disabled="busy"
            @click="onToggle"
            :title="item.is_liked ? '取消点赞' : '点赞'"
          >
            {{ item.is_liked ? '已赞' : '点赞' }}
          </button>
        </div>
      </div>
      <div v-if="item.description" class="note-copy">{{ item.description }}</div>
      <div class="row" style="margin-top: 12px">
        <a class="pill mono" :href="item.cover_url || item.play_url" target="_blank" rel="noreferrer">原图</a>
        <RouterLink class="pill" :to="`/video/${item.id}`">查看笔记 / 评论</RouterLink>
      </div>
    </div>
  </div>
</template>

<style scoped>
.feed-card {
  display: grid;
  gap: 0;
  border: 1px solid rgba(255, 255, 255, 0.12);
  background: rgba(255, 255, 255, 0.06);
  border-radius: 16px;
  overflow: hidden;
  break-inside: avoid;
}

.cover {
  background: rgba(0, 0, 0, 0.25);
  aspect-ratio: 4/5;
}

.cover img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}

.content {
  padding: 12px 12px 14px;
}

.note-copy {
  margin-top: 8px;
  color: rgba(255, 255, 255, 0.78);
  line-height: 1.5;
  display: -webkit-box;
  -webkit-line-clamp: 4;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>

// frontend/src/components/FeedVideoCard.tsx
import { Link } from 'react-router-dom'

import type { FeedVideoItem } from '../api/types'

type Props = {
  item: FeedVideoItem
  canLike: boolean
  busy?: boolean
  onToggleLike: (item: FeedVideoItem) => void
}

export default function FeedVideoCard({ item, canLike, busy, onToggleLike }: Props) {
  return (
    <div className="feed-card">
      <Link className="feed-cover" to={`/video/${item.id}`} aria-label={`查看笔记：${item.title}`}>
        <img src={item.cover_url} alt={item.title} loading="lazy" />
      </Link>
      <div className="feed-content">
        <div className="row spread">
          <div>
            <div className="feed-title">
              <Link to={`/video/${item.id}`}>{item.title}</Link>
            </div>
            <div className="subtle">
              @{item.author.username} · #{item.author.id} · {new Date(item.create_time * 1000).toLocaleString()}
            </div>
          </div>
          <div className="row">
            <span className="pill mono">♥ {item.likes_count}</span>
            {canLike ? (
              <button className="primary" type="button" disabled={busy} onClick={() => onToggleLike(item)} title={item.is_liked ? '取消点赞' : '点赞'}>
                {item.is_liked ? '已赞' : '点赞'}
              </button>
            ) : null}
          </div>
        </div>
        {item.description ? <div className="note-copy clamp">{item.description}</div> : null}
        <div className="row feed-actions">
          <a className="pill mono" href={item.cover_url || item.play_url} target="_blank" rel="noreferrer">
            原图
          </a>
          <Link className="pill" to={`/video/${item.id}`}>
            查看笔记 / 评论
          </Link>
        </div>
      </div>
    </div>
  )
}
