// frontend/src/views/HomeView.vue
<script setup lang="ts">
import { computed, onMounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'

import AppShell from '../components/AppShell.vue'
import FeedVideoCard from '../components/FeedVideoCard.vue'
import { useAuthStore } from '../stores/auth'
import { useToastStore } from '../stores/toast'
import { useVideoFeed } from '../composables/useVideoFeed'
import { useLikeFollow } from '../composables/useLikeFollow'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const toast = useToastStore()

const { tab, following, currentState, loadFollowing, loadLatest, loadHot, ensureTabLoaded } = useVideoFeed()

async function needLogin() {
  toast.error('请先登录')
  await router.push('/account')
}

const { likeBusy, toggleLike } = useLikeFollow(needLogin)

const q = computed(() => (typeof route.query.q === 'string' ? route.query.q.trim().toLowerCase() : ''))
const filteredItems = computed(() => {
  const items = currentState.value.items
  if (!q.value) return items
  return items.filter((v) =>
    [v.title, v.description || '', v.author.username].some((part) => part.toLowerCase().includes(q.value)),
  )
})

const tabCopy = computed(() => {
  if (tab.value === 'following') return '看看你关注的人最近都在发什么图文内容。'
  if (tab.value === 'hot') return '按热度排序，适合展示“爆款图文内容”的效果。'
  return '最新流按发布时间倒序展示图文笔记，适合快速查看社区刚刚更新的内容。'
})

async function refreshCurrentTab() {
  if (tab.value === 'latest') await loadLatest(true)
  else if (tab.value === 'hot') await loadHot(true)
  else await loadFollowing(true)
}

async function loadMoreCurrentTab() {
  if (tab.value === 'latest') await loadLatest(false)
  else if (tab.value === 'hot') await loadHot(false)
  else await loadFollowing(false)
}

async function onPageScroll(event: Event) {
  const el = event.currentTarget as HTMLElement | null
  if (!el || currentState.value.loading || !currentState.value.hasMore) return
  if (el.scrollTop + el.clientHeight >= el.scrollHeight - 240) await loadMoreCurrentTab()
}

watch(() => auth.isLoggedIn, async (v) => {
  if (tab.value === 'following' && v && following.items.length === 0) await loadFollowing(true)
})

watch(() => tab.value, async () => {
  await ensureTabLoaded()
})

onMounted(async () => {
  await ensureTabLoaded()
})
</script>

<template>
  <AppShell full @content-scroll="onPageScroll">
    <div class="page">
      <section class="hero">
        <div>
          <div class="hero-kicker">图文社区 Demo</div>
          <h1 class="hero-title">沉浸式浏览最新图文笔记，快速体验小红书风格社区首页</h1>
          <p class="hero-copy">{{ tabCopy }}</p>
        </div>
        <div class="hero-tabs">
          <button class="tab" :class="{ on: tab === 'latest' }" type="button" @click="tab = 'latest'">最新</button>
          <button class="tab" :class="{ on: tab === 'following' }" type="button" @click="tab = 'following'">关注</button>
          <button class="tab" :class="{ on: tab === 'hot' }" type="button" @click="tab = 'hot'">热榜</button>
        </div>
      </section>

      <section class="stream-head">
        <div class="subtle">
          当前共 {{ filteredItems.length }} 条{{ q ? '匹配到的' : '' }}笔记
          <span v-if="q"> · 搜索词：{{ q }}</span>
        </div>
        <div class="row">
          <button class="chip-btn" type="button" :disabled="currentState.loading" @click="refreshCurrentTab">刷新</button>
          <button class="chip-btn primary" type="button" :disabled="currentState.loading || !currentState.hasMore" @click="loadMoreCurrentTab">
            加载更多
          </button>
        </div>
      </section>

      <div v-if="currentState.loading && currentState.items.length === 0" class="center-hint">加载中…</div>
      <div v-else-if="currentState.error && currentState.items.length === 0" class="center-hint bad">{{ currentState.error }}</div>
      <div v-else-if="filteredItems.length === 0" class="center-hint">没有匹配内容</div>

      <section v-else class="waterfall">
        <FeedVideoCard
          v-for="item in filteredItems"
          :key="`${tab}-${item.id}`"
          :item="item"
          :can-like="auth.isLoggedIn"
          :busy="!!likeBusy[String(item.id)]"
          @toggle-like="toggleLike"
        />
      </section>
    </div>
  </AppShell>
</template>

<style scoped>
.page {
  min-height: 100%;
  padding: 20px 18px 36px;
}

.hero {
  display: grid;
  grid-template-columns: minmax(0, 1fr) auto;
  gap: 18px;
  align-items: end;
  padding: 24px;
  border-radius: 24px;
  border: 1px solid rgba(255, 255, 255, 0.1);
  background:
    radial-gradient(circle at top right, rgba(255, 166, 138, 0.22), transparent 26%),
    radial-gradient(circle at top left, rgba(97, 194, 255, 0.2), transparent 22%),
    linear-gradient(135deg, rgba(255, 255, 255, 0.08), rgba(255, 255, 255, 0.03));
}

.hero-kicker {
  font-size: 12px;
  letter-spacing: 0.18em;
  text-transform: uppercase;
  color: rgba(255, 255, 255, 0.62);
}

.hero-title {
  margin: 8px 0 10px;
  font-size: clamp(26px, 4vw, 40px);
  line-height: 1.05;
}

.hero-copy {
  margin: 0;
  max-width: 680px;
  color: rgba(255, 255, 255, 0.76);
  line-height: 1.6;
}

.hero-tabs {
  display: flex;
  gap: 10px;
  flex-wrap: wrap;
  justify-content: flex-end;
}

.tab,
.chip-btn {
  border: 1px solid rgba(255, 255, 255, 0.12);
  background: rgba(255, 255, 255, 0.06);
  color: rgba(255, 255, 255, 0.9);
  border-radius: 999px;
  padding: 10px 14px;
  cursor: pointer;
}

.tab.on,
.chip-btn.primary {
  border-color: rgba(255, 120, 90, 0.48);
  background: rgba(255, 120, 90, 0.16);
}

.stream-head {
  margin: 18px 0 14px;
  display: flex;
  gap: 14px;
  align-items: center;
  justify-content: space-between;
}

.center-hint {
  min-height: 280px;
  display: grid;
  place-items: center;
  color: rgba(255, 255, 255, 0.78);
}

.center-hint.bad {
  color: rgba(255, 120, 90, 0.96);
}

.waterfall {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 16px;
  align-items: start;
}

.waterfall :deep(.feed-card) {
  min-width: 0;
}

@media (max-width: 1000px) {
  .hero {
    grid-template-columns: 1fr;
  }

  .hero-tabs {
    justify-content: flex-start;
  }

  .waterfall {
    grid-template-columns: repeat(2, minmax(0, 1fr));
  }
}

@media (max-width: 720px) {
  .page {
    padding: 14px 12px 28px;
  }

  .stream-head {
    align-items: flex-start;
    flex-direction: column;
  }

  .waterfall {
    grid-template-columns: 1fr;
  }
}
</style>

// frontend/src/views/HomeView.tsx
import { useEffect, useMemo } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'

import AppShell from '../components/AppShell'
import FeedVideoCard from '../components/FeedVideoCard'
import { useLikeFollow } from '../composables/useLikeFollow'
import { useVideoFeed } from '../composables/useVideoFeed'
import { useAuth } from '../stores/auth'
import { useToast } from '../stores/toast'

export default function HomeView() {
  const auth = useAuth()
  const toast = useToast()
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const { tab, setTab, following, currentState, loadFollowing, loadLatest, loadHot, ensureTabLoaded, replaceItem } = useVideoFeed()

  async function needLogin() {
    toast.error('请先登录')
    await navigate('/account')
  }

  const { likeBusy, toggleLike } = useLikeFollow(needLogin)
  const q = (params.get('q') ?? '').trim().toLowerCase()
  const filteredItems = useMemo(() => {
    if (!q) return currentState.items
    return currentState.items.filter((v) => [v.title, v.description || '', v.author.username].some((part) => part.toLowerCase().includes(q)))
  }, [currentState.items, q])

  useEffect(() => {
    void ensureTabLoaded()
  }, [tab])

  useEffect(() => {
    if (tab === 'following' && auth.isLoggedIn && following.items.length === 0) void loadFollowing(true)
  }, [auth.isLoggedIn, following.items.length, loadFollowing, tab])

  const tabCopy =
    tab === 'following'
      ? '看看你关注的人最近都在发什么图文内容。'
      : tab === 'hot'
        ? '按热度排序，适合展示“爆款图文内容”的效果。'
        : '最新流按发布时间倒序展示图文笔记，适合快速查看社区刚刚更新的内容。'

  async function refreshCurrentTab() {
    if (tab === 'latest') await loadLatest(true)
    else if (tab === 'hot') await loadHot(true)
    else await loadFollowing(true)
  }

  async function loadMoreCurrentTab() {
    if (tab === 'latest') await loadLatest(false)
    else if (tab === 'hot') await loadHot(false)
    else await loadFollowing(false)
  }

  return (
    <AppShell
      full
      onContentScroll={(event) => {
        const el = event.currentTarget
        if (!currentState.loading && currentState.hasMore && el.scrollTop + el.clientHeight >= el.scrollHeight - 240) void loadMoreCurrentTab()
      }}
    >
      <div className="page">
        <section className="hero">
          <div>
            <div className="hero-kicker">图文社区 Demo</div>
            <h1 className="hero-title">沉浸式浏览最新图文笔记，快速体验小红书风格社区首页</h1>
            <p className="hero-copy">{tabCopy}</p>
          </div>
          <div className="hero-tabs">
            <button className={`tab ${tab === 'latest' ? 'on' : ''}`} type="button" onClick={() => setTab('latest')}>
              最新
            </button>
            <button className={`tab ${tab === 'following' ? 'on' : ''}`} type="button" onClick={() => setTab('following')}>
              关注
            </button>
            <button className={`tab ${tab === 'hot' ? 'on' : ''}`} type="button" onClick={() => setTab('hot')}>
              热榜
            </button>
          </div>
        </section>

        <section className="stream-head">
          <div className="subtle">
            当前共 {filteredItems.length} 条{q ? '匹配到的' : ''}笔记{q ? ` · 搜索词：${q}` : ''}
          </div>
          <div className="row">
            <button className="chip-btn" type="button" disabled={currentState.loading} onClick={() => void refreshCurrentTab()}>
              刷新
            </button>
            <button className="chip-btn primary" type="button" disabled={currentState.loading || !currentState.hasMore} onClick={() => void loadMoreCurrentTab()}>
              加载更多
            </button>
          </div>
        </section>

        {currentState.loading && currentState.items.length === 0 ? <div className="center-hint">加载中...</div> : null}
        {currentState.error && currentState.items.length === 0 ? <div className="center-hint bad">{currentState.error}</div> : null}
        {!currentState.loading && !currentState.error && filteredItems.length === 0 ? <div className="center-hint">没有匹配内容</div> : null}
        {filteredItems.length ? (
          <section className="waterfall">
            {filteredItems.map((item) => (
              <FeedVideoCard
                key={`${tab}-${item.id}`}
                item={item}
                canLike={auth.isLoggedIn}
                busy={!!likeBusy[String(item.id)]}
                onToggleLike={(v) => void toggleLike(v, replaceItem)}
              />
            ))}
          </section>
        ) : null}
      </div>
    </AppShell>
  )
}
